Download single file style
puzzle/unilu-pruefungsabfrage pull request #126
Opened 2024-09-30 09:56 UTC by kcinay055679

2024-10-03 10:58 UTC, RandomTannenbaum requested changes

2024-10-03 11:08 UTC, Miguel7373 commented on src/main/resources/templates/fragments/exam-file.html
> +
Done

2024-10-03 11:10 UTC, RandomTannenbaum submitted a review, later dismissed

2024-10-08 09:13 UTC, RandomTannenbaum requested changes

2024-10-08 09:13 UTC, RandomTannenbaum commented on src/main/resources/templates/search.html
> +                th:if="${examFiles != null && examFiles.size() >= 2}"
```suggestion
                th:if="${examFiles != null && examFiles.size() > 0}"
```

2024-10-08 09:14 UTC, ManuelMoeri commented on src/main/resources/templates/search.html
> +                th:if="${examFiles != null && examFiles.size() >= 2}"
:+1:

2024-10-08 09:22 UTC, RandomTannenbaum submitted a review, later dismissed

2024-10-09 06:14 UTC, MasterEvarior requested changes
The code looks good just two things that I've spotted:
- Everything except the subject title (i.e. "Öffentliches Recht") is center aligned. I think it would look better if this is also aligned the same way, which would then also be consistent with the mockup.
- If the subject is very long it gets cut off to the right, which I think this is fine. The user however has no possibility to discerne between to long subject which start the same (i.e. "Öffentliches Recht der Fakultät der modernen Sprachen" and "Öffentliches Recht der Fakultät der modernen Mathematik"). I think the user should be able to tell the difference between the two. Maybe a tooltip would help?
![image](https://github.com/user-attachments/assets/3117244d-79ee-4443-93a4-c65be2dbc04b)

2024-10-09 10:37 UTC, MasterEvarior approved these changes
LGTM :+1:

2024-10-09 10:38 UTC, merged