Feature/122 Header styling
puzzle/unilu-pruefungsabfrage pull request #128
Opened 2024-09-30 11:16 UTC by Miguel7373

2024-09-30 11:39 UTC, RandomTannenbaum requested changes

2024-09-30 11:39 UTC, RandomTannenbaum commented on src/main/resources/templates/fragments/header.html
> +<header class="d-flex p-2 pb-0 align-items-center justify-content-between border-bottom border-dark m-1 pb-3">
```suggestion
<header class="d-flex p-2 pb-0 align-items-center justify-content-between border-bottom border-dark m-4 pb-3">
```

2024-09-30 13:00 UTC, Miguel7373 commented on src/main/resources/templates/fragments/header.html
> +<header class="d-flex p-2 pb-0 align-items-center justify-content-between border-bottom border-dark m-1 pb-3">
Done

2024-09-30 15:18 UTC, peggimann approved these changes

2024-10-01 13:36 UTC, pizzi-cato approved these changes

2024-10-01 13:36 UTC, merged