Feature/1 login anbinden
puzzle/unilu-pruefungsabfrage pull request #149
Opened 2024-10-11 11:06 UTC by RandomTannenbaum

2024-10-18 12:03 UTC, peggimann requested changes

2024-10-18 14:01 UTC, RandomTannenbaum commented on src/main/java/ch/puzzle/eft/config/AppServerConfig.java
> +        connector.setSecure(false);
setSecure only tells the client if the connection itself is secure or not. See: https://tomcat.apache.org/tomcat-8.5-doc/api/org/apache/catalina/connector/Connector.html#setSecure(boolean)

AJP isnt a secure protocol, so I think false is okay:
https://stackoverflow.com/questions/12460422/how-do-ensure-that-apache-ajp-to-tomcat-connection-is-secure-encrypted

2024-10-21 06:56 UTC, RandomTannenbaum commented on src/main/java/ch/puzzle/eft/config/SecurityConfig.java
> +        authenticationFilter.setCheckForPrincipalChanges(false);
When trying to access the application with this option we get "This page is not redirecting properly"

2024-10-21 09:31 UTC, RandomTannenbaum commented on src/main/java/ch/puzzle/eft/config/SecurityConfig.java
> +                Collection<GrantedAuthority> authorities = token.getAuthorities();
I have only ever seen an empty list of authorities in the logs and we also have no role system so afaik we dont need them currently

2024-10-23 09:03 UTC, MasterEvarior commented on pom.xml
> +			<version>3.3.4</version>
Is there a specific reason why all the spring-boot-starter versions are now explicitly mentioned? They should already be automatically configured by the ` spring-boot-starter-parent`.

2024-10-23 09:16 UTC, MasterEvarior approved these changes

2024-10-23 09:19 UTC, merged