Feature/152-cookie-dialog-rework
puzzle/unilu-pruefungsabfrage pull request #155
Opened 2024-10-17 13:01 UTC by Miguel7373

2024-10-18 08:36 UTC, RandomTannenbaum requested changes

2024-10-18 08:36 UTC, RandomTannenbaum commented on src/test/e2e/cypress/e2e/cookie-banner.js
> +        cy.getByTestId("cookie-consent-button").click();
Check if cookie is not set before clicking

2024-10-21 06:28 UTC, peggimann approved these changes

2024-10-21 06:33 UTC, RandomTannenbaum approved these changes

2024-10-23 09:31 UTC, merged