Feature/17 examnumber input
puzzle/unilu-pruefungsabfrage pull request #52
Opened 2024-08-29 08:43 UTC by nevio18324

2024-08-30 11:29 UTC, pizzi-cato commented on src/main/java/ch/puzzle/eft/controller/ValidationController.java
> +public class ValidationController {
Der ValidationController kann ebenso gut in den SiteController integriert werden. Damit haben wir alle wichtigen Requests in demselben Controller.

2024-08-30 11:39 UTC, pizzi-cato requested changes
Muss zusammen mit der Story #12 abgeschlossen werden.
Der ValidationController kann in den SiteController integriert werden.

2024-08-30 11:39 UTC, pizzi-cato commented on src/main/resources/templates/fragments/exam-number-input.html
> +        <input type="text" name="examNumber" id="examNumber" pattern="[0-9]{5}"
Das Pattern kann an dieser Stelle weggelassen werden, weil dieses auch  in der Modellklasse ExamNumberForm definiert ist. Im Controller kann dann geprüft werden, ob die (client-seitige) Validierung einen Fehler hat oder nicht (siehe BindingResult#hasErrors() ).

2024-08-30 11:39 UTC, pizzi-cato commented on src/main/resources/templates/fragments/exam-number-input.html
> +        <button type="submit" id="submitButton">Suchen</button>
Der Button bleibt  immer enabled, sollte aber disabled sein, wenn
a) das Feld leer ist
b) das Feld != 5 Zeichen enthält

2024-08-30 11:39 UTC, pizzi-cato commented on src/main/java/ch/puzzle/eft/controller/ValidationController.java
> +        model
Das Mapping auf "/validate" ist nur ein Teil der Aufgabe. Mit der Suche aus Story #12 kann hier die Suche ausgelöst werden, falls keine Fehler vorliegen (siehe BindingResult#hasErrors() ). Sonst bleiben mir auf der Such-Seite mit entsprechender Fehlermedlung.

2024-09-02 09:10 UTC, nevio18324 commented on src/main/resources/templates/fragments/exam-number-input.html
> +        <button type="submit" id="submitButton">Suchen</button>
Der Button ist kaum umsetzbar mit nur Thymeleaf und würde höchstwahrscheinlich Javascript benötigen weswegen es mit dem Pattern eine Alternative gesucht wurde.

2024-09-03 05:38 UTC, pizzi-cato commented on src/main/java/ch/puzzle/eft/controller/SiteController.java
> +        model
Hier fehlt die Auswertung der Validierung: Liegen Validierungsfehler vor, kehrt die Applikation auf die Suchseite zurück, liegen keine Validierungsfehler vor, wird die Suche ausgeführt und auf die Resultatseite weitergeleitet.

Siehe Beispiel https://spring.io/guides/gs/validating-form-input

2024-09-03 05:42 UTC, pizzi-cato commented on src/main/resources/templates/fragments/exam-number-input.html
> +        <input type="text" name="examNumber" id="examNumber" pattern="[0-9]{5}"
Aktuell validieren wir an drei Stellen: client-seitig anhand des Patterns, server-seitig mit der Methode viewValidatePage(@Valid ...) und schliesslich auch im Validation Service. Gemäss Beispiel https://spring.io/guides/gs/validating-form-input würde ich im Moment auf die client-seitige Validierung verzichten, solange wir nicht Scripts im client verwenden (Validierung, enable / disable Submit Button).

2024-09-09 06:44 UTC, pizzi-cato approved these changes
- Code OK
- Tests OK
- offener Punkt wird gefixt

2024-09-09 06:44 UTC, pizzi-cato commented on src/main/java/ch/puzzle/eft/controller/SiteController.java
> +        model
OK

2024-09-09 06:44 UTC, pizzi-cato commented on src/main/java/ch/puzzle/eft/controller/SiteController.java
> +                                    .getExamNumber(), "11112222"));
Diese ist ein offener Punkt und sollte mit einem Kommentar / TODO gekennzeichnet werden.

2024-09-09 06:44 UTC, pizzi-cato commented on src/main/resources/templates/fragments/exam-number-input.html
> +        <button type="submit" id="submitButton">Suchen</button>
OK, wir lassen im Moment Scripts weg und verzichten auf enable / disable Button.

2024-09-09 06:48 UTC, merged