Feature/16 Zip download
puzzle/unilu-pruefungsabfrage pull request #56
Opened 2024-08-29 13:11 UTC by ManuelMoeri

2024-09-06 10:57 UTC, ManuelMoeri commented
### Stand 06.09.2024
Die Logik & das Testing ist beendet. Das einzige das noch fehlt ist das dazugehörige Frontend. Dies kann aber erst implementiert werden nachdem das Ticket #17 beendet wurde, da der Button zum Herunterladen des ZIP's erst nach dem Suchen auftauchen sollte.

Im moment failed noch der letzte Test im 'ExamFileServiceTest' file. Der Test funktioniert  Lokal problemlos, aber sobald er mit `mvn test -Dtest=ExamFileServiceTest` oder auf der Pipeline ausgeführt wird, failed er. Die Ursache ist klar ersichtlich jedoch nicht wie man diese beheben kann.

2024-09-12 12:23 UTC, pizzi-cato requested changes

2024-09-12 12:23 UTC, pizzi-cato commented on src/main/java/ch/puzzle/eft/service/ExamFileService.java
> +            e.printStackTrace();
Damit wird die Exception "verschluckt" und der Anwender sieht nichts davon.
Korrekt wäre, den Fehler zu loggen (info oder warn) und dann ein 500er Fehler zurückzugeben.

2024-09-12 12:23 UTC, pizzi-cato commented on src/main/java/ch/puzzle/eft/service/ExamFileService.java
> +        List<ExamFileModel> matchingExams = getMatchingExams(examNumber, "11112222");
Hier ist ein TODO sinnvoll, damit die hart codierte Matrikelnummer später durch die aktuelle ersetzt wird.

2024-09-12 12:23 UTC, pizzi-cato commented on src/main/resources/templates/search.html
> +        Download all exams as ZIP
Aktuell verwenden überall Deutsch im UI. Deshalb soll dieser Button angepasst werden.

2024-09-12 12:23 UTC, pizzi-cato commented on src/test/java/ch/puzzle/eft/controller/ExamDownloadControllerTest.java
> +    void download() throws Exception {
Der Methodenname sagt nicht allzu viel aus, was genau getestet werden soll. Typischerweise wird der Methodenname (oder hier auch der Path downloadZip) und der gewünschte Test Case angegeben, z.B. downloadZipShouldReturnZipFile.

2024-09-12 12:23 UTC, pizzi-cato commented on src/test/java/ch/puzzle/eft/service/ExamFileServiceTest.java
> +                assertEquals(expectedContent2, actualContent);
Hier würden alle weiteren Dateien geprüft (>= 2). Da wir nur zwei Dateien erwarten, wäre eine dritte oder vierte Datei ein Fehler. Deshalb sollte der der Fall i > 2 als Fehler aufpoppen.

OK, actualEntries wird mit 2 instanziert, d.h. eine dritte Datei würde bereits zum Fehler führen. Dennoch ist die Implementierung nicht ganz offensichtlich, was im Fall i >2 passieren würde.

2024-09-13 12:39 UTC, pizzi-cato approved these changes

2024-09-13 12:42 UTC, pizzi-cato approved these changes

2024-09-13 12:43 UTC, merged