Use non root user in docker container
puzzle/unilu-pruefungsabfrage pull request #67
Opened 2024-09-10 10:52 UTC by RandomTannenbaum

2024-09-11 12:06 UTC, ManuelMoeri requested changes
Looks good except for the small spelling mistake.
:+1:

2024-09-11 12:06 UTC, ManuelMoeri commented on README.md
> +To now make sure Docker uses the rootless daemon, specify the cli context like this: `docker conext use rootless`.
The command should be 'docker context use rootless'. Small spelling mistake.

2024-09-11 12:26 UTC, ManuelMoeri submitted a review, later dismissed
Nice :100:

2024-09-12 11:40 UTC, pizzi-cato approved these changes

2024-09-12 12:49 UTC, pizzi-cato approved these changes

2024-09-12 12:52 UTC, merged