Sortieren der angezeigten Liste der Prüfungen #46
puzzle/unilu-pruefungsabfrage pull request #90
Opened 2024-09-19 08:02 UTC by Miguel7373

2024-09-19 08:20 UTC, ManuelMoeri reviewed
:100:

2024-09-19 10:59 UTC, pizzi-cato requested changes

2024-09-19 11:20 UTC, Miguel7373 commented on src/main/java/ch/puzzle/eft/service/ExamService.java
> +                            .sorted()
Ich habe einen Comparator hinzugefügt der die subject namen der files alphabetisch sortiert
`.sorted(Comparator.comparing(ExamModel::getSubjectName, String.CASE_INSENSITIVE_ORDER))`

2024-09-20 08:54 UTC, pizzi-cato requested changes

2024-09-20 08:54 UTC, pizzi-cato commented on src/main/java/ch/puzzle/eft/service/ExamService.java
> +                            .sorted(Comparator.comparing(ExamModel::getSubjectName, String.CASE_INSENSITIVE_ORDER))
Case INsensitive ist OK. Die Umlaute werden aber immer noch am Schluss der Liste angefügt, was im deutschsprachingen Raum ungewöhnlich ist. 

Die Umlaute müssen ebenfalls in der richtigen Reihenfolge erscheinen, d.h. ä bei a, ö bei o und ü bei u.

2024-09-20 13:06 UTC, pizzi-cato requested changes

2024-09-20 13:06 UTC, pizzi-cato commented on src/test/java/ch/puzzle/eft/service/ExamServiceTest.java
> +        for (int i = 0; i < expectedFileNames.size(); i++) {
OK, das ist die hard coded Variante.

Es gibt in JUnit und AssertJ Methoden, die den Vergleich von Collections erlauben.

2024-09-20 14:00 UTC, pizzi-cato approved these changes

2024-09-20 14:00 UTC, merged